# Generated by Django 6.0.4 on 2026-06-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PixelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=80, unique=True)),
                ('advertiser_id', models.CharField(db_index=True, max_length=80)),
                ('event_type', models.CharField(max_length=80)),
                ('user_id', models.CharField(db_index=True, max_length=120)),
                ('page_url', models.URLField(max_length=2048)),
                ('referrer', models.URLField(blank=True, max_length=2048)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='web', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
