# Generated by Django 6.0.4 on 2026-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pixelevent',
            name='user_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
